config/routes.rb
Ipro369MoJo::Application.routes.draw do

  resources :item_descriptions
  resources :item_histories
  resources :items
  resources :images
  resources :bagtypes
  resources :users
  resources :locations
  resources :interactions
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "pages#home", :as => "home_page"

  match '/leaderboards/users' => 'pages#top_drops_by_user', :as => :leaderboards_users_path
  match '/leaderboards/items' => 'pages#top_hops_by_item', :as => :leaderboards_items_path
  match '/leaderboards/distance' => 'pages#running_distance_by_item', :as => :leaderboards_distance_path
  match '/items_admin/multiNew' => 'items#multi_new_random', :as => :items_multinew_path
  match '/items_admin/multi_create' => 'items#multi_create_scatter', :via => :post
  post '/items_admin/mn_specific' => 'items#multi_create_specific', :as => :mn_specific_path
  match '/items_admin/multiNewSpecific' => 'items#multi_new_specific', :as => :items_multinew_specific
  match '/items_admin/master_map' => 'items#master_map', :as => :master_map_path
  match '/signup' => 'users#new', :as => :signup_path
  match '/login' => 'sessions#new', :as => :login_path
  match '/logout' => 'sessions#destroy', :as => :logout_path
  match '/backpack' => 'items#backpack', :as => :backpack_path
  match '/history' => 'items#user_item_history', :as => :user_history_path
  match '/admin' => 'pages#admin', :as => :admin_portal_path
  match '/about' => 'pages#about', :as => :about_path

  match '/demo/mapanimation' => 'pages#map_animation'
  match '/demo/canvasmap' => 'pages#canvas_map'
  match '/api/allHistory' => 'item_histories#mapHistory', :format => 'json'
  match '/api/demo/itemDensity' => 'items#density', :format => 'json'
  match '/demo/densitymap' => 'pages#density_map'
### API Methods ###
  match '/api/pickupItem' => 'items#pickup', :format => 'json'
  match '/api/dropItem' => 'items#drop', :format => 'json'
  match '/api/getItemDetails/:id' => 'item_histories#itemDetails', :format => 'json'
  match '/api/getItemDetails' => 'item_histories#itemDetails', :format => 'json'
  match '/api/getBackpackItems' => 'items#backpack', :format => 'json'
  match '/api/getItemsNearBy' => 'items#nearby', :format => 'json'
  match '/api/recordLocation' => 'locations#record_location', :format => 'json'
  match '/api/getImage' => 'images#getImage', :format => 'json'
  match '/api/locationPing/:latitude/:longitude/:timestamp' => 'locations#record_location', :format => 'json'
  match '/api/registerUser' => 'users#create', :format => 'json'
  match '/api/login' => 'sessions#create', :as => 'api_login', :format => 'json'
  match '/api/logout' => 'sessions#destroy', :as => 'api_logout', :format => 'json'
  match '/api/getLocationsForRange' => 'locations#get_locations_for_range', :format => 'json'
  match '/api/getLocationsForRangeInArea' => 'locations#get_locations_for_range_in_area', :format => 'json'
  match '/api/writeInteraction' => 'interactions#create', :format => 'json'
  match '/api/getItemDescription' => 'item_descriptions#show', :format => 'json'
  match '/api/getDescriptionUpdates' => 'item_descriptions#get_description_updates', :format => 'json'
  match '/api/loginToSite' => 'sessions#create_by_app'

end


app/views/pages/_leaderboards_header.html.erb

<div class="left leaderboard_nav">
  <ul class="left">
    <li>
      <%= link_to "Most Hops", :leaderboards_items_path %>
    </li>
	<li>
      <%= link_to "Farthest Traveled", :leaderboards_distance_path %>
    </li>
    <li>
      <%= link_to "Most Drops", :leaderboards_users_path %>
    </li>
  </ul>
</div>
<div class="left" style="width:100%">
<h2 class="left white tpage"><%= @title %></h2>
</div>

app/views/pages/about.html.erb
<video src="https://s3.amazonaws.com/media.serendipity/IproWIthoutSidt+With+Audio.mov"></video>

app/views/pages/admin.html.erb
<span class="title2">Serendipity | </span>
<span class="title2"> Admin</span>

<br><br>



<div class="admin_nav blue">
	<ul>	
		<li><%= link_to "Manage Users", users_path %></li>
		<li><%= link_to "Manage Item Icons", images_path %></li>
		<li><%= link_to "Manage Item Descriptions", item_descriptions_path %></li>
		<li><%= link_to "Manage Items", items_path %></li>
		<li><%= link_to "Manage Item Histories", item_histories_path %></li>
		<li><%= link_to "Manage Locations", locations_path %></li>
		<li><%= link_to "Manage Interactions", interactions_path %></li>
	</ul>
</div>

app/views/pages/canvasmap.html.erb
	<style type="text/css">
		canvas { border: 1px solid black; }
	</style>
  <script type="application/javascript">

  // animation
  var ctx = null;
  var canvas = null;
  var canvasx = 520;
  var canvasy = 360;

  // Amount per draw to move a point
  var geographical_step = 0.01;

  // Real time per draw
  var time_step = 50;

  // "Map time" per draw
  var geographical_time_step = 1;

  var current_time = 0;

  var centerLat = 0;
  var centerLng = 0;
  var overallZoom = 1;
  var backdrop = new Image();
  backdrop.src = 'http://maps.googleapis.com/maps/api/staticmap?center='+centerLat+','+centerLng+'&zoom='+overallZoom+'&size='+canvasx+'x'+canvasy+'&sensor=false&scale=1';
  var current_time = 0;


  var xOffset = 180;
  var xScale = 2;
  var yOffset = 90;
  var yScale = 2;

  // Takes in real latitude/longitude, turns it into X/Y coordinates on canvas/draws it
  function drawDot(context, lat, lng) {
    var drawScale = canvasy;
    var x = (((lng - (centerLng-(180/overallZoom)))/(360/overallZoom))*canvasx);
    var y = (((centerLat + (90/overallZoom) - lat)/(180/overallZoom))*canvasy);
    //var x = xScale*(lng - centerLat);
    //var y = canvasy - yScale*(lat - centerLat);
    context.beginPath();
    context.arc(x,y,10,0,Math.PI*2,true);
    context.fillStyle = 'red';
    context.fill();
  }

var points = [
// Center real
{ state: 0, lng: NaN, lat: NaN, Vlng: NaN, Vlat: NaN, path: [{ lng: -86.6266956329346, lat: 41.8373648878959, time: 0}, { lng: -87.6266956329346, lat: 43.8373648878959, time: 10}] },

{ state: 0, lng: NaN, lat: NaN, Vlng: NaN, Vlat: NaN, path: [{ lng: -87.6266956329346, lat: 41.8373648878959, time: 0}, { lng: -87.6266956329346, lat: 41.8373648878959, time: 10}] },

  // Stalat in center
//{ state: 0, lng: NaN, lat: NaN, Vlng: NaN, Vlat: NaN, path: [{ lng: 0, lat: 0, time: 0}, {lng:0, lat:0, time: 20}] },
  // Corner -> Center -> Corner..

/*{ state: 0, lng: NaN, lat: NaN, Vlng: NaN, Vlat: NaN,
path: [
      { lng: 0,	lat: 0, time: 0},
      {lng: 180,lat: 90,time: 20},
      {lng: 0,lat: 0,time: 40},
      {lng: -180,lat: -90,time: 60},
      {lng: 0,	lat: 0,time: 100},
      {lng: 180,lat: -90,time: 120},
      {lng: 0,	lat: 0,time: 140	},
      {lng: -180,lat: 90,	time: 160},
      {lng: 0,	lat: 0,time: 180}
      ]
}, 

  // Four corners
{state: 0, lng: NaN, lat: NaN, Vlng: NaN, Vlat: NaN, path: [{lng: 180, lat: 90, time: 0}, {lng: 180, lat: -90, time: 40}, {lng: -180, lat: -90, time: 80}, {lng: -180, lat: 90, time: 100}, {lng:180, lat:90, time: 120}]}
*/
];
function init() { 
  canvas = document.getElementById('animap');
  if (canvas.getContext) {
    ctx = canvas.getContext('2d');
  }
  setTimeout(draw, time_step);
}


function timeToMove(p) {
  return (current_time >= p.path[0].time && typeof p.path[1] != 'undefined');
}

function calculateVelocity(p, pathSrc, pathDest) {
  var time_for_move = (pathDest.time - pathSrc.time);
  p.Vlat =  (pathDest.lat - pathSrc.lat)/(time_for_move * geographical_time_step);
  p.Vlng =  (pathDest.lng - pathSrc.lng)/(time_for_move * geographical_time_step);
  // if this point hasn't been drawn yet
  if (isNaN(p.lat) || isNaN(p.lng)) {
    p.lat = pathSrc.lat;
    p.lng = pathSrc.lng;
  }
  p.path.splice(0,1) // remove src from path list, we don't need that anymore
}

function destReached(src,dest,tollerance) {
  return (Math.abs(src + 180) - tollerance < Math.abs(dest + 180) && Math.abs(src + 180) + tollerance > Math.abs(dest + 180));
}

function calculateOffset(p) {
  p.lat = p.lat + (p.Vlat * geographical_time_step);
  p.lng = p.lng + (p.Vlng * geographical_time_step);
}

function draw() {
  ctx.clearRect(0, 0 ,canvasx, canvasy);
  ctx.drawImage(backdrop,0,0);
  for (i in points) {
    p = points[i];
    if (p.state == 0) {
      // Point is not in motion

      if (timeToMove(p)) {
        p.state = 1;
        // Calculate velocity
        calculateVelocity(p, p.path[0], p.path[1]);
        console.log("Time to move!");
      }
    }
    if (p.state == 1) {
      // Point is in motion

      // Note: We shouldn't have to check both X and Y
      if (!destReached(p.lat, p.path[0].lat, geographical_step) || !destReached(p.lng, p.path[0].lng, geographical_step)) {
        calculateOffset(p);
      } else {
        console.log("Destination reached, bravo!");
        p.state = 0;
      }
    }
    drawDot(ctx, p.lat, p.lng);
  }

  current_time = current_time + geographical_time_step;
  setTimeout(draw, time_step);
}


</script>
<canvas id="animap" width="520" height="360"></canvas>

<script>$(function() { init(); })</script>

app/views/pages/density_map.html.erb
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=drawing"></script>

<script type="text/javascript">
var map;
var point;
var colors = [{max: 0, color: "#00000"}, {max: 20, color: "#FFD9E2"}, {max: 90, color: "#FCB1C4"}, {max: 120, color: "#FFA1B8"}, {max: 200, color: "#FF85A3"}, {max: 400, color: "#FF4271"}, {max: 800, color: "#FF124D"}, {max: 1000, color: "#FF003F"}];

function initialize() {
  console.log("Initializing..");
  // Create a map, center it
  map = new google.maps.Map(document.getElementById('map_canvas'),{ zoom: 2, mapTypeId: google.maps.MapTypeId.ROADMAP });
  map.setCenter(new google.maps.LatLng(41.83579, -87.62654));
  map.setZoom(14);
  var drawingManager = new google.maps.drawing.DrawingManager({
    drawingMode: google.maps.drawing.OverlayType.CIRCLE,
    drawingControl: true,
    drawingControlOptions: {
    position: google.maps.ControlPosition.TOP_CENTER,
    drawingModes: [google.maps.drawing.OverlayType.CIRCLE]
    },
    circleOptions: {
    fillColor: '#ffff00',
    fillOpacity: 0.4,
    strokeWeight: 1,
    clickable: false,
    zIndex: 1,
    editable: false
    }
  });
  drawingManager.setMap(map);
  function densityToColor(i, r) {
    var density = i/r;
    var color = colors[0];
    for (i in colors) {
      if (density > colors[i].max) {
        color = colors[i].color;
      }
    }
    return color;
  }
  function metersToMiles(m) {
    return m * 0.000621371192;
  }
  google.maps.event.addListener(drawingManager, 'circlecomplete', function(circle) {
    var lat = circle.getCenter().Pa
    var lng = circle.getCenter().Qa
    var radius = metersToMiles(circle.getRadius())
    var friendlyRadius = radius.toFixed(2)
    if (friendlyRadius == 0) friendlyRadius = " < 0";
    $.get('/api/demo/itemDensity', {latitude: lat, longitude: lng, distance: radius}, 
      function(data) {
        circle.fillColor = densityToColor(data.density, radius);
        circle.setMap(map);
        
          var marker = new google.maps.Marker({
                  position: new google.maps.LatLng(lat,lng),
                  map: map,
                  title: "" + data.density + " items within " + friendlyRadius + " miles"
                  });
          var infowindow = new google.maps.InfoWindow({
              content: "<b>" + data.density + "</b> items within <b>" + friendlyRadius + "</b> miles"

            });
          google.maps.event.addListener(marker, 'click', function() { infowindow.open(map,marker); });
      });
  });
  // http://haacked.com/archive/2009/12/29/convert-rgb-to-hex.aspx
  function colorToHex(color) {
    if (color.substr(0, 1) === '#') {
      return color;
    }
    var digits = /(.*?)rgb\((\d+), (\d+), (\d+)\)/.exec(color);

    var red = parseInt(digits[2]);
    var green = parseInt(digits[3]);
    var blue = parseInt(digits[4]);

    var rgb = blue | (green << 8) | (red << 16);
    return digits[1] + '#' + rgb.toString(16);
  };
}


google.maps.event.addDomListener(window, 'load', initialize);

$(function() {
for (i in colors) {
  var elm = '<div style="background-color: '+ colors[i].color +'"> &#8776; ' + colors[i].max + ' items/mi</div>';
  $('#legend').append(elm);
}
});
</script>
<h2 class="left white tpage">Item Density Map</h2>
<div>
<div style="width:600px; height:600px; display: inline-block;"> 
<div id="map_canvas" style="width:100%; height:100%"></div> 
</div> 
<div style="width: 150px; display: inline-block; float:right;">
<div style="">
<h2 class ="left white tpage">Legend</h2>
<div id="legend">

</div>
</div>
</div>
</div>

app/views/pages/items.html.erb
<h1>Leaderboards - Items</h1>

Top Drops
<table>
  <tr>
    <th>Item ID</th>
    <th>Drops</th>
    <th></th>
  </tr>

<% @TopItems.each do |item| %>
  <tr>
    <td><%= item.item_id %></td>
    <td><%= item.item_count %></td>
  </tr>
<% end %>
</table>
<br/>




app/views/pages/items2.html.erb
<h1>Leaderboards - Items</h1>

Top Locations
<table>
  <tr>
    <th>Item ID</th>
    <th>Running Distance</th>
    <th></th>
  </tr>

<% @TopLocations.each do |item| %>
  <tr>
    <td><%= item.runningdistance %></td>
    <td><%= item.item_distance %></td>
  </tr>
<% end %>
</table>
<br/>

app/views/pages/map_animation.html.erb
<script type="text/javascript">
var map;
var point;

function initialize() {
  console.log("Initializing..");
  // Create a map, center it
  map = new google.maps.Map(document.getElementById('map_canvas'),{ zoom: 2, mapTypeId: google.maps.MapTypeId.ROADMAP });
  map.setCenter(new google.maps.LatLng(0,0));

  // Empty array, will hold data for animation in following form:
  // [{marker: google.maps.Marker, dest: google.maps.LatLng, callback: function (data, id)}]
  var motion_data = Array();

  // Helper method to populate motion_data	
  function addPath(srclat, srclng, destlat, destlng, data, map, callback) {
    data.push({marker: (new google.maps.Marker({position: (new google.maps.LatLng(srclat,srclng)), map: map})), 
        dest: (new google.maps.LatLng(destlat,destlng)),
        callback: callback})
  }
  // Some data!
  addPath(30,30,10,1,motion_data,map, function(data, id) { data[id].dest = new google.maps.LatLng(40,-87); data[id].done = false; callback = undefined;} );
  addPath(-10,-10,-30,-40,motion_data,map);
  addPath(-1,2,20,-5,motion_data,map);
  addPath(14,-1,50,4, motion_data,map);

  // Helper method, calculates if we've reached the spot we want to get to
  function isHit(source, dest, step) {
    return (Math.abs(source) - step < Math.abs(dest) && Math.abs(source) + step > Math.abs(dest))
  }

  // Iterates through data to move markers about map
  function animateStep(data, step_size, step_length) {
    for (id in data) {
      var md = data[id];
      if (md.done) continue;

      var lat = md.marker.position.lat();
      var lng = md.marker.position.lng();

      // Calculate how much we need to move by

      // NOTE: This doesn't work as well as we'd like, does not create a straight line
      // Do some trig here or something...
      if (!isHit(md.marker.position.lat(), md.dest.lat(), step_size))
        lat = (md.marker.position.lat() < md.dest.lat()) ? (md.marker.position.lat() + step_size) : (md.marker.position.lat() - step_size);
      if (!isHit(md.marker.position.lng(), md.dest.lng(), step_size))
        lng = (md.marker.position.lng() < md.dest.lng()) ? (md.marker.position.lng() + step_size) : (md.marker.position.lng() - step_size);
      // If we decided it needs to be moved, move it
      if (lat != md.marker.position.lat() || lng != md.marker.position.lng()) {
        md.marker.setPosition(new google.maps.LatLng(lat,lng));
      } else {
        md.done = true;
        if ((typeof md.callback) == "function") {
          md.callback(data, id);
        }
      }
    }
    window.setTimeout(function() { animateStep(data, step_size) }, step_length);
  }

  // Kick off the animation
  window.setTimeout(function() { animateStep(motion_data, 0.1, 50) }, 1000);
}   

//window.setTimeout(function() { initialize() }, 1000);
google.maps.event.addDomListener(window, 'load', initialize);

</script>
<div style="width:600px; height:600px;"> 
<div id="map_canvas" style="width:100%; height:100%"></div> 
</div> 

app/views/pages/mapanimation.html.erb
<script type="text/javascript">
var map;
var point;

function initialize() {
  console.log("Initializing..");
  // Create a map, center it
  map = new google.maps.Map(document.getElementById('map_canvas'),{ zoom: 2, mapTypeId: google.maps.MapTypeId.ROADMAP });
  map.setCenter(new google.maps.LatLng(0,0));

  // Empty array, will hold data for animation in following form:
  // [{marker: google.maps.Marker, dest: google.maps.LatLng, callback: function (data, id)}]
  var motion_data = Array();

  // Helper method to populate motion_data	
  function addPath(srclat, srclng, destlat, destlng, data, map, callback) {
    data.push({marker: (new google.maps.Marker({position: (new google.maps.LatLng(srclat,srclng)), map: map})), 
        dest: (new google.maps.LatLng(destlat,destlng)),
        callback: callback})
  }
  // Some data!
  addPath(30,30,10,1,motion_data,map, function(data, id) { data[id].dest = new google.maps.LatLng(40,-87); data[id].done = false; callback = undefined;} );
  addPath(-10,-10,-30,-40,motion_data,map);
  addPath(-1,2,20,-5,motion_data,map);
  addPath(14,-1,50,4, motion_data,map);

  // Helper method, calculates if we've reached the spot we want to get to
  function isHit(source, dest, step) {
    return (Math.abs(source) - step < Math.abs(dest) && Math.abs(source) + step > Math.abs(dest))
  }

  // Iterates through data to move markers about map
  function animateStep(data, step_size, step_length) {
    for (id in data) {
      var md = data[id];
      if (md.done) continue;

      var lat = md.marker.position.lat();
      var lng = md.marker.position.lng();

      // Calculate how much we need to move by

      // NOTE: This doesn't work as well as we'd like, does not create a straight line
      // Do some trig here or something...
      if (!isHit(md.marker.position.lat(), md.dest.lat(), step_size))
        lat = (md.marker.position.lat() < md.dest.lat()) ? (md.marker.position.lat() + step_size) : (md.marker.position.lat() - step_size);
      if (!isHit(md.marker.position.lng(), md.dest.lng(), step_size))
        lng = (md.marker.position.lng() < md.dest.lng()) ? (md.marker.position.lng() + step_size) : (md.marker.position.lng() - step_size);
      // If we decided it needs to be moved, move it
      if (lat != md.marker.position.lat() || lng != md.marker.position.lng()) {
        md.marker.setPosition(new google.maps.LatLng(lat,lng));
      } else {
        md.done = true;
        if ((typeof md.callback) == "function") {
          md.callback(data, id);
        }
      }
    }
    window.setTimeout(function() { animateStep(data, step_size) }, step_length);
  }

  // Kick off the animation
  window.setTimeout(function() { animateStep(motion_data, 0.1, 50) }, 1000);
}   

//window.setTimeout(function() { initialize() }, 1000);
google.maps.event.addDomListener(window, 'load', initialize);

</script>
<div style="width:600px; height:600px;"> 
<div id="map_canvas" style="width:100%; height:100%"></div> 
</div> 

app/views/pages/running_distance_by_item.html.erb
<%= render 'leaderboards_header' %>


<table style="background:#3C9CFF;" class="resize_rarity">
  <tr style="background:#3C9CFF">
    <th>Rank</th>
    <th>Item</th>
    <th>Rarity</th>
    <th>Distance</th>
    <th>Description</th>
    <th>Last Message</th>
  </tr>

  <% @top_items.each_with_index do |row, index| %>
      <tr>
        <td><h2 class="white"><%= index + 1 %></h2></td>
        <td><%= image_tag row[:image] %></td>
        <td><%= image_tag "rarity_icons/bg-#{row[:rarity]}.png" %></td>
        <td><%= row[:distance] %></td>
        <td style="text-align:left">
          Item Name: <%= row[:name] %>
          <br>
          Last Drop date: <%= row[:drop_date] %>
          <br>
          Rarity: <%= row[:rarity] %>
          <br>
          Hops: <%= row[:hops] %>
          <br>
        </td>
        <td><%= row[:last_message] %></td>
      </tr>
  <% end %>
</table>
<br/>

app/views/pages/running_distance_by_user.html.erb
<h1>Leaderboards - Users</h1>



<span class="left white"><h1>Top Locations</h1></span>


<table>
  <tr>
    <th>User ID</th>
    <th>Running Distance</th>
    <th></th>
  </tr>

<% @top_users.each do |item| %>
  <tr>
    <td><%= user.user_id %></td>
    <td><%= user.user_count%></td>
  </tr>
<% end %>
</table>
<br/>

app/views/pages/top_drops_by_user.html.erb
<%= render 'leaderboards_header' %>

<div style="width:100%; height:120px;padding-bottom:30px">
    <div class="left green white" style="padding:5px;border-radius:5px;">
		My Total Drops # of: 
	</div>
	<div class="left green white" style="padding:5px;border-radius:5px;">
		<%= current_user.item_histories.count %>
  	</div>
</div>

<!--<div class="left white"><h1>World Leaderboard<h1></div>-->

<div class="leaderboard" style="width:100%">
  <div>
    <div>
      <table style=" background:gray;">
        <tr style="background:gray">
          <th>Rank</th>
          <th>Username</th>
          <th>Drops</th>
          <th>Last Message</th>
        </tr>
        <% @top_users.each_with_index do |user, index| %>
            <tr>
              <td class="rank">
                <%= index + 1 %>
              </td>
              <td><%= user[:username] %></td>
              <td><%= user[:drops] %></td>
              <td><%= user[:last_message] %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
  <br><br>
</div>

app/views/pages/users.html.erb
<h1>Leaderboards - Users</h1>

Top Drops
<table>
  <tr>
    <th>User ID</th>
    <th>Drops</th>
  </tr>

<% @TopUsers.each do |user| %>
  <tr>
    <td><%= user.user_id %></td>
    <td><%= user.user_count %></td>

  </tr>
<% end %>
</table>
<br/>




app/views/pages/users2.html.erb
<h1>Leaderboards - Users</h1>

Top Locations
<table>
  <tr>
    <th>User ID</th>
    <th>Running Distance</th>
    <th></th>
  </tr>

<% @TopUsers.each do |item| %>
  <tr>
    <td><%= user.user_id %></td>
    <td><%= user.user_count%></td>
  </tr>
<% end %>
</table>
<br/>