config/routes.rb
Ipro369MoJo::Application.routes.draw do

  resources :item_descriptions
  resources :item_histories
  resources :items
  resources :images
  resources :bagtypes
  resources :users
  resources :locations
  resources :interactions
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "pages#home", :as => "home_page"

  match '/leaderboards/users' => 'pages#top_drops_by_user', :as => :leaderboards_users_path
  match '/leaderboards/items' => 'pages#top_hops_by_item', :as => :leaderboards_items_path
  match '/leaderboards/distance' => 'pages#running_distance_by_item', :as => :leaderboards_distance_path
  match '/items_admin/multiNew' => 'items#multi_new_random', :as => :items_multinew_path
  match '/items_admin/multi_create' => 'items#multi_create_scatter', :via => :post
  post '/items_admin/mn_specific' => 'items#multi_create_specific', :as => :mn_specific_path
  match '/items_admin/multiNewSpecific' => 'items#multi_new_specific', :as => :items_multinew_specific
  match '/items_admin/master_map' => 'items#master_map', :as => :master_map_path
  match '/signup' => 'users#new', :as => :signup_path
  match '/login' => 'sessions#new', :as => :login_path
  match '/logout' => 'sessions#destroy', :as => :logout_path
  match '/backpack' => 'items#backpack', :as => :backpack_path
  match '/history' => 'items#user_item_history', :as => :user_history_path
  match '/admin' => 'pages#admin', :as => :admin_portal_path
  match '/about' => 'pages#about', :as => :about_path

  match '/demo/mapanimation' => 'pages#map_animation'
  match '/demo/canvasmap' => 'pages#canvas_map'
  match '/api/allHistory' => 'item_histories#mapHistory', :format => 'json'
  match '/api/demo/itemDensity' => 'items#density', :format => 'json'
  match '/demo/densitymap' => 'pages#density_map'
### API Methods ###
  match '/api/pickupItem' => 'items#pickup', :format => 'json'
  match '/api/dropItem' => 'items#drop', :format => 'json'
  match '/api/getItemDetails/:id' => 'item_histories#itemDetails', :format => 'json'
  match '/api/getItemDetails' => 'item_histories#itemDetails', :format => 'json'
  match '/api/getBackpackItems' => 'items#backpack', :format => 'json'
  match '/api/getItemsNearBy' => 'items#nearby', :format => 'json'
  match '/api/recordLocation' => 'locations#record_location', :format => 'json'
  match '/api/getImage' => 'images#getImage', :format => 'json'
  match '/api/locationPing/:latitude/:longitude/:timestamp' => 'locations#record_location', :format => 'json'
  match '/api/registerUser' => 'users#create', :format => 'json'
  match '/api/login' => 'sessions#create', :as => 'api_login', :format => 'json'
  match '/api/logout' => 'sessions#destroy', :as => 'api_logout', :format => 'json'
  match '/api/getLocationsForRange' => 'locations#get_locations_for_range', :format => 'json'
  match '/api/getLocationsForRangeInArea' => 'locations#get_locations_for_range_in_area', :format => 'json'
  match '/api/writeInteraction' => 'interactions#create', :format => 'json'
  match '/api/getItemDescription' => 'item_descriptions#show', :format => 'json'
  match '/api/getDescriptionUpdates' => 'item_descriptions#get_description_updates', :format => 'json'
  match '/api/loginToSite' => 'sessions#create_by_app'

end


app/models/item_description.rb
# == Schema Information
#
# Table name: item_descriptions
#
#  id          :integer         primary key
#  name        :string(255)
#  description :text
#  rarity      :string(255)
#  image_id    :integer
#  created_at  :timestamp
#  updated_at  :timestamp
#

class ItemDescription < ActiveRecord::Base

  belongs_to :image
  has_many :items, :dependent => :destroy

validates :name, :uniqueness => true
validates :description, :presence => true
validates :rarity, :presence => true
validates :image_id, :presence => true

  def thumb
    image.icon.url(:thumb)
  end

end

app/controllers/item_descriptions_controller.rb
require 'sessions_helper'

class ItemDescriptionsController < ApplicationController
  include SessionsHelper

  before_filter :admin_login_required, :except => [:show, :get_description_updates]
  before_filter :admin_or_app_required, :only => :show
  before_filter :app_required, :only => :get_description_updates

  # GET /item_descriptions
  # GET /item_descriptions.json
  def index
    @item_descriptions = ItemDescription.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @item_descriptions }
    end
  end

  # GET /item_descriptions/1
  # GET /item_descriptions/1.json
  def show
    @item_description = ItemDescription.find(params[:id]) if ItemDescription.exists?(params[:id])
    @lats = []
    @longs = []
    @item_descriptions = Item.find_all_by_item_description_id(@item_description.id).paginate(:page => params[:page], :per_page => 1000) if @item_description

    @item_descriptions.each do |item|
      @lats << item.latitude
      @longs << item.longitude
    end if @item_descriptions

    respond_to do |format|
      format.html # show.html.erb
      format.json do
        if @item_description
          render json: @item_description, :status => :ok
        else
          render json: "None Found", :status => :not_found
        end
      end
    end
  end

  # GET /item_descriptions/new
  # GET /item_descriptions/new.json
  def new
    @item_description = ItemDescription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item_description }
    end
  end

  # GET /item_descriptions/1/edit
  def edit
    @item_description = ItemDescription.find(params[:id])
  end

  # POST /item_descriptions
  # POST /item_descriptions.json
  def create
    @item_description = ItemDescription.new(params[:item_description])

    respond_to do |format|
      if @item_description.save
        format.html { redirect_to @item_description, notice: 'Item description was successfully created.' }
        format.json { render json: @item_description, status: :created, location: @item_description }
      else
        format.html { render action: "new" }
        format.json { render json: @item_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /item_descriptions/1
  # PUT /item_descriptions/1.json
  def update
    @item_description = ItemDescription.find(params[:id])

    respond_to do |format|
      if @item_description.update_attributes(params[:item_description])
        format.html { redirect_to @item_description, notice: 'Item description was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_descriptions/1
  # DELETE /item_descriptions/1.json
  def destroy
    @item_description = ItemDescription.find(params[:id])
    @item_description.destroy

    respond_to do |format|
      format.html { redirect_to item_descriptions_url }
      format.json { head :ok }
    end
  end

  def get_description_updates
    if params[:dateTime].blank?
      render :json => ItemDescription.all, :status => :ok
    else
      descriptions = ItemDescription.where("updated_at > ?", params[:dateTime].to_datetime.to_s(:db))
      if descriptions.first
        render :json => descriptions, :status => :ok
      else
        render :json => "No Updates Found", :status => :ok
      end
    end
  end
end

app/helpers/item_descriptions_helper.rb
module ItemDescriptionsHelper
end

app/views/item_descriptions/_form.html.erb
<%= form_for(@item_description) do |f| %>
  <% if @item_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_description.errors.count, "error") %> prohibited this item_description from being saved:</h2>

      <ul>
      <% @item_description.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rarity %><br />
    <%= f.text_field :rarity %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br />
    <%= f.number_field :image_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_descriptions/edit.html.erb
<h1>Editing item_description</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_description %> |
<%= link_to 'Back', item_descriptions_path %>

app/views/item_descriptions/index.html.erb
<h1 style="width:100%; text-align:left;">Listing Item Descriptions</h1>

<span class="white orange button"><%= link_to 'CREATE New Item description', new_item_description_path %></span>
<br><br>

<%= will_paginate %>
<br>
<table>
  <tr>
    <th>Name</th>
    <th>Icon</th>
	<th>Description</th>
    <th>Rarity</th>
    <th>Map</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @item_descriptions.each do |item_description| %>
  <tr>
    <td><%= item_description.name %></td>
    <td><%= item_description.description %></td>
    <td><%= item_description.rarity %></td>
    <td><%= item_description.image_id %></td>
    <td>
		<span class="button white orange">
			<%= link_to 'Show', item_description %>
		</span>
	</td>
    <td>
		<span class="button white black">
			<%= link_to 'Edit', edit_item_description_path(item_description) %>
		</span>
		</td>
    <td>
		<span class="red button white">
			<%= link_to 'Destroy', item_description, confirm: 'Are you sure?', method: :delete %>
		</span>
	</td>
  </tr>
<% end %>
</table>

<%= will_paginate %>

<br />

app/views/item_descriptions/new.html.erb
<h1>New item_description</h1>

<%= render 'form' %>
<br><br><br><br>
<span class="white">
<%= link_to 'Back', item_descriptions_path %>
</span>

app/views/item_descriptions/show.html.erb
<span class="left white orage button"><%= link_to 'Edit', edit_item_description_path(@item_description) %></span>
<span class="left white orage button"><%= link_to 'Back', item_descriptions_path %></span>
<br><br><br><br>

<div class="left" style="text-align:left">
	<p id="notice"><%= notice %></p>

	<p>
	  <b>ID :</b>
	  <%= @item_description.id %>
	</p>

	<p>
	  <b>Name:</b>
	  <%= @item_description.name %>
	</p>

	<p>
	  <b>Description:</b>
	  <%= @item_description.description %>
	</p>

	<p>
	  <b>Rarity:</b>
	  <%= @item_description.rarity %>
	</p>

	<p>
	  <b>Image:</b>
	  <%= @item_description.image_id %>
	</p>
</div>

<script type="text/javascript">
    var map;
      var lons = <%= @longs.as_json %>;
      var lats = <%= @lats.as_json %>;
    function initialize() {

        var myOptions = {
            zoom: 8,
            center: new google.maps.LatLng(41.83872375564222, -87.62723207473755),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

        for(var i=0; i<lons.length; i++) {
            placeMarker(new google.maps.LatLng(lats[i], lons[i]));
        }

        function placeMarker(location) {
            var marker = new google.maps.Marker({
                position: location,
                map: map,
                animation: google.maps.Animation.DROP
            });
            google.maps.event.addListener(marker, 'click', function() {
                map.setZoom(8);
            });
        }
    }

    $(document).ready(function () {
        console.log("loaded dom");
        initialize();
    });

</script>

<%= will_paginate %>

<div style="width:500px; height:500px;">
  <div id="map_canvas" style="width:100%; height:100%"></div>
</div>

<%= will_paginate %>